# Generated by Django 4.2.28 on 2026-03-28 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_attribute_alter_product_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Атрибут товара', 'verbose_name_plural': 'Атрибуты товаров'},
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop_app.attribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Значение'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value',
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
